learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

#template taggging
app_name='basicapp'

urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls'))
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'Welcome to the new year','number':2020,'text_new':"Hello World"}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{%url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{%url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{%url 'basicapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block%}
    <div class="jumbotron">
      <h1>Django Level Five</h1>
    </div>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to other!!</h1>
    <h1>This is an example of template inheritance</h1>
  {% endblock %}

learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative URL templates</h1>
    <a href="{%url 'basicapp:other' %}">THE OTHER_PAGE</a>
    <a href="{%url 'admin:index' %}">Go to the admin page</a>
    <a href="{%url 'index' %}">Go to the index page</a> 
  </body>
</html>